### ISSUE TITLE
Does it work with wso2 sp 4.4.0 ?

### ISSUE THREAD

**Issue by xuhai-sy** [wso2-extensions/siddhi-gpl-execution-geo#38]
**Description:**

I am learning wso2 sp 4.4.0. Does siddhi-gpl-execution-geo support wso2 4.4.0 ?

**Comment by niveathika** [comment]
@xuhai-sy Yes, the latest version of the siddhi-gpl-execution-geo - [v4.0.9](https://mvnrepository.com/artifact/org.wso2.extension.siddhi.gpl.execution.geo/siddhi-gpl-execution-geo/4.0.9) works with SP4.4.0-mX releases.

**Comment by NisalaNiroshana** [comment]
I hope our answer will help you resolve your issue. If you have any concerns or issues, please reopen the issue and get back to us.
